deviceName: Nymph

http:
  bindHost: "0.0.0.0"
  bindPort: 3000
  baseUrl: "http://localhost:3000"

bridge:
  public: false

relays:
  - discord: "996069746514612235"
    matrix: "!yTRzUDNyviBhrMwYGG:matrix.org"

bridgeProvider:
  discord:
    enable: false
    appId: ""
    botToken: ""

  matrix:
    enable: false
    homeserverUrl: "https://matrix.org"
    accessToken: ""

  line:
    enable: false
    channelAccessToken: ""
    channelSecret: ""

  anthropic:
    enable: false
    apiKey: ""
    model: "claude-3-5-sonnet-20241022"
